#!/bin/sh

opkg update
opkg install netbird
netbird login --setup-key ключ
/etc/init.d/netbird enable
/etc/init.d/netbird start
uci -q delete network.NetBird
uci set network.NetBird=interface
uci set network.NetBird.proto='none'
uci set network.NetBird.device='wt0'
uci commit
